### ISSUE TITLE
Design proposal to support gauges (dynamic measures)

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-specs#59] opened 2018-02-28 19:57 UTC
Explain how can open-census support recording measurements that are not event based such as task_memory_usage, task_cpu_usage.

**Comment by songy23** [comment] 2019-03-13 02:51
Duplicate of https://github.com/census-instrumentation/opencensus-specs/issues/240.

**Closed by songy23** 2019-03-13 02:51 UTC
Labels: documentation, stats
